mysql_root_password: "!QAZxsw2#EDC"
wordpress_database_name: "wordpress"
wordpress_database_user: "wordpress"
wordpress_database_password: "123@wordpress"
wordpress_admin_username: "admin"
wordpress_admin_password: "123@admin"
domain_name: test.io
