---
- hosts: test
  become: yes

  vars_files:
    - group_vars/all_vault.yml


  roles:
    - { role: predeploy, tags: [predeploy]}
    - { role: nginx, tags: [nginx]}   
    - { role: mysql, tags: [mysql]}
    - { role: wordpress, tags: [wordpress]}
